### ISSUE TITLE
Data source name not found and no default driver specified

### ISSUE THREAD

**Issue by harshdattani** [udacity/nd081-c1-provisioning-microsoft-azure-vms-project-starter#2]
Error in line 17 of config.py. Updating it to `SQLALCHEMY_DATABASE_URI = 'mssql+pyodbc://' + SQL_USER_NAME + '@' + SQL_SERVER + ':' + SQL_PASSWORD + '@' + SQL_SERVER + ':1433/' + SQL_DATABASE  + '?driver=SQL+Server'  has solved the error in windows.
`

**Comment by mvirgo** [comment]
Thanks for the note for Windows users! As noted in the comment above this line, it has to be updated based on your OS. The driver currently listed is for Mac and Linux.

**Comment by SudKul** [comment]
Fixed in this [commit](https://github.com/udacity/nd081-c1-provisioning-microsoft-azure-vms-project-starter/commit/13bc1357fecb22bda1f558a364551e4b6721cb17).
